sudo: false

language: php

php:
  - 7.2
  - 7.3
  - 7.4

install:
  - travis_retry composer install --no-interaction
  - composer info -i

jobs:
  include:
    - stage: Static analysis (src) with phpstan
      php: 7.2
      script: vendor/bin/phpstan analyse

    - stage: Test
      php: 7.2
      script: vendor/bin/phpunit

    - stage: Test_74
      php: 7.4
      script: vendor/bin/phpunit

